import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"
import JotaiProvider from "../components/providers/jotai-provider";
import { GlobalAlert } from "@/components/layouts/alert";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Certificate Management System | VBNN Smart Education Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <JotaiProvider>
          {children}
          <Toaster />
          <GlobalAlert/>
        </JotaiProvider>
      </body>
    </html>
  );
}
