import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import AuthGuard from "@/components/wrappers/authGuard";
import Header from "@/components/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full ">
              <SidebarTrigger className="fixed" />
              <Header/>
              <div className="p-8">{children}</div>
            </main>
          </SidebarProvider>
        </AuthGuard>
      </body>
    </html>
  );
}
